using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RumineSimulator_2._0
{
    enum Traits
    {
        programmer,
        arter,      
        pooper,
        letsplayer,
        linuxoid,
        windusiatnik,
        jew,
        ucraine,
        russian,
        serb,
        bidla,
        nigga,
        memguy,
        sadboi,
        vilka,
        inteligent,
        nazi,
        nevecherya,
        natural,
        animeshnik,
        kachok,
        kazah,
        belorus,
        furry,
        pane,
        ded,
        Wpower,
        katleta,
        reper,
        teacher,
        major,
        pirate,
        rom,
        bomj,
        writer,
        karmodroch,
        alkash,
        srednefag,
        newfag,
        rak,
        madguy,
        revolutioner,
        konserva,
        kindguy,
        fashik,
        commie,
        leader,
        accurateguy,
        gaymer,
        kebabremover,
        newslover,
        gaymmaker,
        tiran,            
        atheist,
        christ,
        krab,
        asket,
        gnomik,
        tea,
        composer,
        notrait,

        sociofob,
        veteran,
        ancient,
        flooder,
        lazyguy,
        nitik,
        critic,
        historic,
        scintist,
        gym,
        tech,
        neutral,
        imperor,
    }
    enum TraitType
    {
        notype,

        oldness,

        proffesional,
        chRak,
        chAdeq,
        chCons,
        chTolerance,
        holywar,
        nation,
        character,

    }
}
